spring.application.name=RemitlyStockMarket
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=drop-and-create
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never